### PR TITLE
Fix test failing on travis because of build tools upgrade

### PR DESCRIPTION
**Pull request by danielgomezrico**
Downgraded to 23.0.0

### CODE REVIEW

**Comment by danielgomezrico** [comment]
Should fix https://github.com/kevalpatel2106/LandscapeVideoCamera/pull/1 completelly

**Comment by kevalpatel2106** [comment]
Looks good. Let me see if it works.

**Comment by kevalpatel2106** [comment]
Cheers!!! Build is successfully compiled.

image

Thank you very much.

**Comment by danielgomezrico** [comment]
😀

**Comment by kevalpatel2106** [comment]
But the coverage decreased by about 4%.

**Comment by danielgomezrico** [comment]
Yeah, I changed the tests so they work for the old cases, not the new ones with front facing camera, there are missing tests, I mean, when you pass `true` to `isFront` everywhere

**Pull request merged**
